language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/phpunit

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm-3.18
          sudo: required
          dist: trusty
          group: edge

cache:
    directories:
        - .phpunit
